version: 0.2

phases:
  install:
    runtime-versions:
      java: 17

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - export REPOSITORY_URI=205930651657.dkr.ecr.us-east-1.amazonaws.com/abhiram-registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(date +%Y%m%d%H%M%S)  # Unique timestamp-based tag to avoid conflicts

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=SpringbootDataJpaRelationships
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/SpringbootDataJpaRelationships.jar
