version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y java-17-amazon-corretto-devel
      - java -version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto"
      - export PATH=$JAVA_HOME/bin:$PATH
      - export REPOSITORY_URI=205930651657.dkr.ecr.us-east-1.amazonaws.com/abhiram-registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(date +%Y%m%d%H%M%S)

  build:
    commands:
      - echo "Building Java application..."
      - mvn clean install -DskipTests
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Build completed successfully!"